### ISSUE TITLE
Error in stage 4

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-sqlite#55]
```
[stage-4] Running tests for Stage #4: Count rows in a table
[stage-4] Creating table 'chocolate' with 0 rows
panic: strings: negative Repeat count

goroutine 26 [running]:
strings.Repeat({0x748ee4, 0x7c67f0}, 0xc0000aa000)
    /opt/hostedtoolcache/go/1.17.13/x64/src/strings/strings.go:529 +0x4d8
github.com/codecrafters-io/sqlite-tester/internal.testRowCounts(0xc00010dd40)
    /home/runner/work/sqlite-tester/sqlite-tester/internal/stage_row_counts.go:45 +0x285
github.com/codecrafters-io/tester-utils.testRunner.Run.func1()
    /home/runner/go/pkg/mod/github.com/codecrafters-io/tester-utils@v0.2.10/test_runner.go:63 +0x2e
created by github.com/codecrafters-io/tester-utils.testRunner.Run
    /home/runner/go/pkg/mod/github.com/codecrafters-io/tester-utils@v0.2.10/test_runner.go:62 +0x368
CodeCrafters internal error: exit status 2
```

**Comment by rohitpaulk** [comment]
Looks like we've got a random value that's too low?
